version: "3.8"
secrets:
  mainzelliste.docker.conf:
    file: ./mainzelliste.docker.conf
services:
  mainzelliste-gui:
    image: medicalinformatics/mainzelliste-gui:develop
    ports:
      - "80:80"
    environment:
      NGINX_SERVER_NAME: localhost
      MAINZELLISTE_URL: http://localhost:8080
      MAINZELLISTE_API_KEY: changeThisApiKey
    depends_on:
      - mainzelliste
  mainzelliste:
    image: medicalinformatics/mainzelliste:develop
    ports:
      - "8080:8080"
    environment:
      ML_API_KEY: changeThisApiKey
      ML_DB_HOST: mainzelliste-db
      ML_DB_PASS: mainzelliste
      ML_ALLOWED_ORIGINS: "http://localhost"
    depends_on:
      - mainzelliste-db
    secrets:
      - mainzelliste.docker.conf
  mainzelliste-db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: mainzelliste
      POSTGRES_USER: mainzelliste
      POSTGRES_PASSWORD: mainzelliste
