version: "3.8"
services:
  mainzelliste-gui:
    image: medicalinformatics/mainzelliste-gui
    build: .
    ports:
      - "80:80"
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_PORT: 80
    depends_on:
      - mainzelliste
  mainzelliste:
    image: medicalinformatics/mainzelliste:develop
    ports:
      - "8080:8080"
    environment:
      ML_API_KEY: changeThisApiKey
      ML_DB_HOST: mainzelliste-db
      ML_DB_PASS: mainzelliste
    depends_on:
      - mainzelliste-db
  mainzelliste-db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: mainzelliste
      POSTGRES_USER: mainzelliste
      POSTGRES_PASSWORD: mainzelliste



