version: "3.8"
secrets:
  mainzelliste.docker.conf:
    file: ./mainzelliste.docker.conf
volumes:
  keycloakDB:
services:
  mainzelliste-gui:
    image: docker.verbis.dkfz.de/ttp/mainzelliste-gui:consent
    ports:
      - "80:80"
    environment:
      NGINX_SERVER_NAME: ${HOST}
      MAINZELLISTE_URL: http://${HOST}:8080
      KEYCLOAK_URL: http://${HOST}:8082
      KEYCLOAK_REALM: mainzelliste
      KEYCLOAK_CLIENT_ID: mainzelliste-ui
    depends_on:
      - mainzelliste
  mainzelliste:
    image: docker.verbis.dkfz.de/ttp/mainzelliste:consent-fhir-jakarta
    ports:
      - "8080:8080"
    environment:
      TOMCAT_REVERSEPROXY_FQDN: ${HOST}
      TOMCAT_REVERSEPROXY_SSL: "false"
      ML_API_KEY: pleaseChangeMeToo
      ML_DB_HOST: mainzelliste-db
      ML_DB_PASS: pleaseChangeMe
      RELAXED_QUERY_CHARS: \|
      ML_ALLOWED_ORIGINS: http://${HOST}
      ML_OIDC_ISS: http://${HOST}:8082/realms/mainzelliste
      ML_OIDC_INTERNAL_ISS_BASE_URL: http://keycloak:8080
    depends_on:
      - mainzelliste-db
    secrets:
      - mainzelliste.docker.conf
  mainzelliste-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mainzelliste
      POSTGRES_USER: mainzelliste
      POSTGRES_PASSWORD: pleaseChangeMe
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    ports:
      - "8082:8080"
    command: ["start-dev"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_DB_URL: jdbc:postgresql://keycloak-db/keycloak
      KC_FEATURES: token-exchange
    volumes:
      - ./resources/keycloak/themes/mainzelliste.jar:/opt/keycloak/providers/mainzelliste.jar
  keycloak-db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - keycloakDB:/var/lib/postgresql/data
