version: "3.8"
secrets:
  mainzelliste.docker.conf:
    file: ./mainzelliste.docker.conf
services:
  mainzelliste-gui:
    image: docker.verbis.dkfz.de/pseudonymisierung/mainzelliste-gui:develop
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_PORT: 80
      NGINX_DEPLOYMENT_CONTEXT: /
    depends_on:
      - mainzelliste
  mainzelliste:
    image: medicalinformatics/mainzelliste:develop
    environment:
      ML_API_KEY: changeThisApiKey
      ML_DB_HOST: mainzelliste-db
      ML_DB_PASS: mainzelliste
      ML_ALLOWED_ORIGINS: "http://localhost:4200"
    depends_on:
      - mainzelliste-db
    secrets:
      - mainzelliste.docker.conf
  mainzelliste-db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: mainzelliste
      POSTGRES_USER: mainzelliste
      POSTGRES_PASSWORD: mainzelliste
